server:
  port: ${SERVICE_PORT:8080}

spring:

  application:
    name: spring-security

  main:
    banner-mode: off

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 40000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: postgresql

  liquibase:
    enabled: true
    drop-first: false
    default-schema: public

  security:
    user:
      name: ${USER_NAME:user}
      password: ${USER_PASSWORD:password}

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    show-extensions: true
    operations-sorter: method
  paths-to-match:
    - /user/**
    - /actuator/health

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

api-info:
  contact-email: "albatovkonstantin@yandex.ru"
  contact-url: "https://idk.com"
  contact-name: "Albatov Konstantin"
  description: "Spring Security App On Steroids"
  external-docs-description: "External docs :)"
  license-url: "https://idk.com"
  external-docs-url: "https://idk.com"
  license-name: "License Name"
  title: "Spring Security"
  version: "v0.0.1"