global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: redis
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
  - job_name: postgres
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

rule_files:
  - /rule_files/*.yml