-- liquibase formatted sql

-- changeset User:1707086884142-1
CREATE TABLE "users"
(
    "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdat" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "email"     VARCHAR(125)                            NOT NULL,
    "name"      VARCHAR(30)                             NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

