name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  form-reports:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Detekt
        run: ./gradlew detekt
      - name: Run KtLint
        run: ./gradlew ktlintcheck

      - name: Upload Detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt_report
          path: ${{ github.workspace }}/build/reports/detekt/detekt.html

      - name: Upload KtLint report
        uses: actions/upload-artifact@v2
        with:
          name: ktlint_report
          path: ${{ github.workspace }}/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.html

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test build
        run: ./gradlew build

  build_with_docker_and_upload:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag springsecurity:latest

      - name: Upload image
        uses: ishworkh/container-image-artifact-upload@v1.0.0
        with:
          image: "springsecurity:latest"

